# Generated by Django 4.1.5 on 2023-01-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_tracker_backend', '0002_alter_friend_friend1_alter_friend_friend2'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
